import { DspParams } from './types';

export const DEFAULT_DSP_PARAMS: DspParams = {
  input_gain_db: 0,
  eq_low_shelf_gain_db: 0,
  eq_low_mid_gain_db: 0,
  eq_high_mid_gain_db: 0,
  eq_high_shelf_gain_db: 0,
  ms_side_high_gain_db: 0,
  ms_mid_low_gain_db: 0,
  comp_threshold_db: -18,
  comp_ratio: 2.5,
  comp_attack_sec: 0.01,
  comp_release_sec: 0.15,
  limiter_ceil_db: -1,
  transformer_saturation: 0,
  transformer_mix: 0,
  triode_drive: 0,
  triode_bias: 0,
  triode_mix: 0,
  tape_saturation: 0,
  tape_mix: 0,
  dyn_eq_enabled: 0,
  stereo_low_mono: 0,
  stereo_high_wide: 1,
  stereo_width: 1,
  parallel_wet: 0
};

export const DSP_PARAM_RANGES: Record<keyof DspParams, { min: number; max: number; step: number }> = {
  input_gain_db: { min: -12, max: 12, step: 0.1 },
  eq_low_shelf_gain_db: { min: -6, max: 6, step: 0.1 },
  eq_low_mid_gain_db: { min: -6, max: 6, step: 0.1 },
  eq_high_mid_gain_db: { min: -6, max: 6, step: 0.1 },
  eq_high_shelf_gain_db: { min: -6, max: 6, step: 0.1 },
  ms_side_high_gain_db: { min: -6, max: 6, step: 0.1 },
  ms_mid_low_gain_db: { min: -6, max: 6, step: 0.1 },
  comp_threshold_db: { min: -40, max: -6, step: 0.1 },
  comp_ratio: { min: 1, max: 8, step: 0.1 },
  comp_attack_sec: { min: 0.001, max: 0.1, step: 0.001 },
  comp_release_sec: { min: 0.05, max: 1, step: 0.01 },
  limiter_ceil_db: { min: -3, max: -0.1, step: 0.1 },
  transformer_saturation: { min: 0, max: 1, step: 0.01 },
  transformer_mix: { min: 0, max: 1, step: 0.01 },
  triode_drive: { min: 0, max: 1, step: 0.01 },
  triode_bias: { min: 0, max: 1, step: 0.01 },
  triode_mix: { min: 0, max: 1, step: 0.01 },
  tape_saturation: { min: 0, max: 1, step: 0.01 },
  tape_mix: { min: 0, max: 1, step: 0.01 },
  dyn_eq_enabled: { min: 0, max: 1, step: 1 },
  stereo_low_mono: { min: 0, max: 1, step: 1 },
  stereo_high_wide: { min: 0, max: 2, step: 0.1 },
  stereo_width: { min: 0, max: 2, step: 0.1 },
  parallel_wet: { min: 0, max: 0.5, step: 0.01 }
};
